[package]
name = "shared"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
bs58 = "0.5.1"
ed25519-dalek = { version = "2.1.1", features = ["rand_core"] }
hex = "0.4.3"
k256 = { version = "0.13.4", features = ["ecdsa"] }
serde = { version = "1.0.219", features = ["derive"] }
tiny-keccak = { version = "2.0.2", features = ["keccak"] }
